// =============================================================
// Comprehensive Granular Permissions & Role Definitions Registry
// Multi-Tenant SaaS Accounting & ERP Platform
// =============================================================

export interface PermissionDefinition {
  code: string
  module: string
  nameAr: string
  nameEn: string
  nameTr: string
  descriptionAr: string
  descriptionEn: string
  descriptionTr: string
  action: 'view' | 'create' | 'edit' | 'delete' | 'manage' | 'post' | 'export'
}

export interface PermissionModuleGroup {
  moduleId: string
  nameAr: string
  nameEn: string
  nameTr: string
  icon: string
  permissions: PermissionDefinition[]
}

export const SYSTEM_PERMISSIONS_REGISTRY: PermissionModuleGroup[] = [
  {
    moduleId: 'sales',
    nameAr: 'المبيعات وعروض الأسعار',
    nameEn: 'Sales & Quotations',
    nameTr: 'Satışlar ve Teklifler',
    icon: 'ShoppingCart',
    permissions: [
      {
        code: 'sales.view',
        module: 'sales',
        nameAr: 'عرض فواتير وعروض المبيعات',
        nameEn: 'View Invoices & Quotations',
        nameTr: 'Satış Faturalarını Görüntüle',
        descriptionAr: 'استعراض قائمة فواتير المبيعات والاطلاع على تفاصيلها',
        descriptionEn: 'View sales invoices and quotation lists and details',
        descriptionTr: 'Satış faturaları ve teklif listelerini görüntüleme',
        action: 'view',
      },
      {
        code: 'sales.create',
        module: 'sales',
        nameAr: 'إنشاء فواتير وعروض جديدة',
        nameEn: 'Create Invoices & Quotations',
        nameTr: 'Fatura ve Teklif Oluştur',
        descriptionAr: 'تحرير وإصدار فواتير المبيعات وعروض الأسعار للعملاء',
        descriptionEn: 'Issue new sales invoices and quotations',
        descriptionTr: 'Yeni satış faturası ve teklif düzenleme',
        action: 'create',
      },
      {
        code: 'sales.edit',
        module: 'sales',
        nameAr: 'تعديل فواتير المبيعات',
        nameEn: 'Edit Sales Invoices',
        nameTr: 'Faturaları Düzenle',
        descriptionAr: 'تعديل بيانات وأسعار وبنود الفواتير غير المؤكدة',
        descriptionEn: 'Edit draft and unpaid sales invoice data',
        descriptionTr: 'Taslak fatura bilgilerini düzenleme',
        action: 'edit',
      },
      {
        code: 'sales.delete',
        module: 'sales',
        nameAr: 'إلغاء وحذف فواتير المبيعات',
        nameEn: 'Cancel & Delete Invoices',
        nameTr: 'Faturaları İptal Et / Sil',
        descriptionAr: 'إلغاء الفواتير أو شطبها من النظام',
        descriptionEn: 'Void or remove sales invoices from the system',
        descriptionTr: 'Satış faturalarını iptal etme veya silme',
        action: 'delete',
      },
      {
        code: 'sales.returns',
        module: 'sales',
        nameAr: 'إدارة مرتجعات المبيعات',
        nameEn: 'Manage Sales Returns',
        nameTr: 'Satış İadelerini Yönet',
        descriptionAr: 'إصدار إشعارات دائنة وإدارة مرتجعات بضائع العملاء',
        descriptionEn: 'Issue credit notes and manage customer product returns',
        descriptionTr: 'Satış iade faturaları ve alacak dekontu düzenleme',
        action: 'manage',
      },
    ],
  },
  {
    moduleId: 'purchases',
    nameAr: 'المشتريات وأوامر الشراء',
    nameEn: 'Purchases & Purchase Orders',
    nameTr: 'Satın Alma ve Siparişler',
    icon: 'ShoppingBag',
    permissions: [
      {
        code: 'purchases.view',
        module: 'purchases',
        nameAr: 'عرض فواتير المشتريات',
        nameEn: 'View Purchase Bills',
        nameTr: 'Satın Alma Faturalarını Gör',
        descriptionAr: 'استعراض فواتير وأوامر الشراء من الموردين',
        descriptionEn: 'Browse vendor bills and purchase orders',
        descriptionTr: 'Tedarikçi faturalarını ve siparişlerini görüntüleme',
        action: 'view',
      },
      {
        code: 'purchases.create',
        module: 'purchases',
        nameAr: 'تسجيل فواتير مشتريات جديدة',
        nameEn: 'Create Purchase Bills',
        nameTr: 'Satın Alma Faturası Gir',
        descriptionAr: 'إدخال فواتير الشراء واستلام بضائع الموردين',
        descriptionEn: 'Record incoming vendor bills and receive goods',
        descriptionTr: 'Yeni satın alma faturası ve mal kabul girişi',
        action: 'create',
      },
      {
        code: 'purchases.edit',
        module: 'purchases',
        nameAr: 'تعديل فواتير المشتريات',
        nameEn: 'Edit Purchase Bills',
        nameTr: 'Satın Alma Faturasını Düzenle',
        descriptionAr: 'تعديل كميات وأسعار بنود فواتير الشراء المسجلة',
        descriptionEn: 'Modify quantities, prices and lines on purchase bills',
        descriptionTr: 'Satın alma faturası kalemlerini ve fiyatlarını düzenleme',
        action: 'edit',
      },
      {
        code: 'purchases.delete',
        module: 'purchases',
        nameAr: 'إلغاء وحذف فواتير المشتريات',
        nameEn: 'Cancel & Delete Bills',
        nameTr: 'Faturaları İptal Et / Sil',
        descriptionAr: 'إلغاء فواتير الشراء ومسودات الموردين',
        descriptionEn: 'Cancel purchase bills and vendor drafts',
        descriptionTr: 'Satın alma faturalarını iptal etme veya silme',
        action: 'delete',
      },
    ],
  },
  {
    moduleId: 'customers',
    nameAr: 'إدارة العملاء والمدينين',
    nameEn: 'Customers & CRM',
    nameTr: 'Müşteriler ve Cari Hesaplar',
    icon: 'Users',
    permissions: [
      {
        code: 'customers.view',
        module: 'customers',
        nameAr: 'عرض سجلات العملاء وكشوفات الحساب',
        nameEn: 'View Customers & Statements',
        nameTr: 'Müşterileri ve Ekstreleri Gör',
        descriptionAr: 'الاطلاع على بيانات العملاء وأرصدتهم وكشوفات حساباتهم',
        descriptionEn: 'View customer contact details, balances and account statements',
        descriptionTr: 'Müşteri bilgilerini, bakiyelerini ve ekstrelerini görme',
        action: 'view',
      },
      {
        code: 'customers.manage',
        module: 'customers',
        nameAr: 'إضافة وتعديل وحذف العملاء',
        nameEn: 'Manage Customer Records',
        nameTr: 'Müşteri Ekle / Düzenle / Sil',
        descriptionAr: 'تسجيل عملاء جدد وتعديل الحدود الائتمانية والبيانات',
        descriptionEn: 'Create, update and manage customer accounts and credit limits',
        descriptionTr: 'Müşteri kartı açma, düzenleme ve kredi limitlerini belirleme',
        action: 'manage',
      },
    ],
  },
  {
    moduleId: 'suppliers',
    nameAr: 'إدارة الموردين والدائنين',
    nameEn: 'Suppliers & Vendors',
    nameTr: 'Tedarikçiler ve Satıcılar',
    icon: 'Truck',
    permissions: [
      {
        code: 'suppliers.view',
        module: 'suppliers',
        nameAr: 'عرض سجلات الموردين وأرصدتهم',
        nameEn: 'View Suppliers & Statements',
        nameTr: 'Tedarikçileri ve Ekstreleri Gör',
        descriptionAr: 'استعراض بيانات الموردين وأرصدتهم المستحقة',
        descriptionEn: 'View vendor records, due balances and statements',
        descriptionTr: 'Tedarikçi kartlarını, borç bakiyelerini ve ekstreleri görme',
        action: 'view',
      },
      {
        code: 'suppliers.manage',
        module: 'suppliers',
        nameAr: 'إضافة وتعديل وحذف الموردين',
        nameEn: 'Manage Supplier Records',
        nameTr: 'Tedarikçi Ekle / Düzenle / Sil',
        descriptionAr: 'تسجيل موردين جدد وتعديل شروط الدفع والبيانات',
        descriptionEn: 'Add, update and manage vendor data and payment terms',
        descriptionTr: 'Tedarikçi kartı açma, düzenleme ve ödeme koşullarını yönetme',
        action: 'manage',
      },
    ],
  },
  {
    moduleId: 'inventory',
    nameAr: 'المخزون والمنتجات والمستودعات',
    nameEn: 'Inventory & Warehouses',
    nameTr: 'Stok ve Depolar',
    icon: 'Package',
    permissions: [
      {
        code: 'inventory.view',
        module: 'inventory',
        nameAr: 'عرض المنتجات وأرصدة المخزون',
        nameEn: 'View Products & Stock Balances',
        nameTr: 'Ürünleri ve Stokları Gör',
        descriptionAr: 'استعراض قائمة المنتجات وأرصدة المخازن والأسعار',
        descriptionEn: 'View product catalog, quantities in stock and prices',
        descriptionTr: 'Ürün listesini, depo stok miktarlarını ve fiyatları görme',
        action: 'view',
      },
      {
        code: 'inventory.manage',
        module: 'inventory',
        nameAr: 'إضافة وتعديل المنتجات والتسعير',
        nameEn: 'Manage Products & Pricing',
        nameTr: 'Ürün ve Fiyat Yönetimi',
        descriptionAr: 'إضافة منتجات جديدة وتعديل التكاليف وأسعار البيع',
        descriptionEn: 'Create products, edit costs, barcodes and sales prices',
        descriptionTr: 'Yeni ürün kartı açma, maliyet ve satış fiyatı belirleme',
        action: 'manage',
      },
      {
        code: 'inventory.adjust',
        module: 'inventory',
        nameAr: 'إجراء تسويات وجرد وتحويلات المخزون',
        nameEn: 'Stock Adjustments & Transfers',
        nameTr: 'Stok Sayımı ve Depolar Arası Transfer',
        descriptionAr: 'تسجيل تسويات الفروقات الجردية ونقل البضائع بين المستودعات',
        descriptionEn: 'Perform physical inventory counts, adjustments and warehouse transfers',
        descriptionTr: 'Stok sayım farkı düzeltme ve depolar arası transfer yapma',
        action: 'manage',
      },
    ],
  },
  {
    moduleId: 'treasury',
    nameAr: 'الخزينة والمقبوضات والمدفوعات',
    nameEn: 'Treasury & Payments',
    nameTr: 'Kasa, Banka ve Ödemeler',
    icon: 'Landmark',
    permissions: [
      {
        code: 'treasury.view',
        module: 'treasury',
        nameAr: 'عرض الصناديق والحسابات البنكية وحركاتها',
        nameEn: 'View Cash, Banks & Transactions',
        nameTr: 'Kasa ve Banka Hesaplarını Gör',
        descriptionAr: 'الاطلاع على أرصدة الخزائن والبنوك وحركات المقبوضات والمدفوعات',
        descriptionEn: 'View cash drawer balances, bank accounts and transaction history',
        descriptionTr: 'Kasa ve banka hesap bakiyelerini ve hareketlerini görme',
        action: 'view',
      },
      {
        code: 'payments.incoming',
        module: 'treasury',
        nameAr: 'تسجيل سندات القبض من العملاء',
        nameEn: 'Record Customer Receipts',
        nameTr: 'Tahsilat Makbuzu Kes',
        descriptionAr: 'استلام الدفعات النقدية والبنكية وتخصيصها على الفواتير',
        descriptionEn: 'Record incoming customer payments and allocate to invoices',
        descriptionTr: 'Müşteri tahsilatlarını kaydetme ve faturalarla eşleştirme',
        action: 'create',
      },
      {
        code: 'payments.outgoing',
        module: 'treasury',
        nameAr: 'تسجيل سندات الصرف للموردين',
        nameEn: 'Record Vendor Payments',
        nameTr: 'Tedarikçi Ödeme Makbuzu',
        descriptionAr: 'صرف المستحقات للموردين وتسديد فواتير الشراء',
        descriptionEn: 'Pay vendor bills and record outbound payments',
        descriptionTr: 'Tedarikçi ödemelerini yapma ve faturaları kapatma',
        action: 'create',
      },
      {
        code: 'treasury.transfers',
        module: 'treasury',
        nameAr: 'التحويل بين الخزائن والحسابات البنكية',
        nameEn: 'Treasury Transfers',
        nameTr: 'Hesaplar Arası Virman',
        descriptionAr: 'إجراء تحويلات مالية وإيداعات بين الصناديق والبنوك',
        descriptionEn: 'Perform internal transfers between bank and cash accounts',
        descriptionTr: 'Banka ve kasa hesapları arasında para transferi yapma',
        action: 'manage',
      },
      {
        code: 'treasury.reconcile',
        module: 'treasury',
        nameAr: 'المطابقات والتسويات البنكية',
        nameEn: 'Bank Reconciliations',
        nameTr: 'Banka Mutabakatı',
        descriptionAr: 'استيراد كشوفات الحسابات البنكية وإجراء المطابقة الآلية',
        descriptionEn: 'Import bank statements and perform ledger reconciliation',
        descriptionTr: 'Banka ekstrelerini yükleme ve hesap mutabakatı yapma',
        action: 'manage',
      },
    ],
  },
  {
    moduleId: 'accounting',
    nameAr: 'المحاسبة والقيود وشجرة الحسابات',
    nameEn: 'General Ledger & Chart of Accounts',
    nameTr: 'Genel Muhasebe ve Hesap Planı',
    icon: 'BookOpen',
    permissions: [
      {
        code: 'accounting.view',
        module: 'accounting',
        nameAr: 'عرض شجرة الحسابات ودفتر الأستاذ وميزان المراجعة',
        nameEn: 'View Chart of Accounts & General Ledger',
        nameTr: 'Hesap Planı ve Kebir Defterini Gör',
        descriptionAr: 'استعراض الحسابات المالية، دليل الحسابات، ودفاتر الأستاذ',
        descriptionEn: 'View standard chart of accounts, ledgers and trial balance',
        descriptionTr: 'Hesap planını, mizanı ve büyük defteri görüntüleme',
        action: 'view',
      },
      {
        code: 'accounting.chart_manage',
        module: 'accounting',
        nameAr: 'إضافة وتعديل وحذف حسابات الشجرة',
        nameEn: 'Manage Chart of Accounts Hierarchy',
        nameTr: 'Hesap Planını Düzenle',
        descriptionAr: 'إنشاء حسابات فرعية جديدة وتعديل خصائص شجرة الحسابات',
        descriptionEn: 'Create, modify and organize accounts in the chart hierarchy',
        descriptionTr: 'Yeni alt hesap açma ve hesap planı hiyerarşisini düzenleme',
        action: 'manage',
      },
      {
        code: 'journal_entries.create',
        module: 'accounting',
        nameAr: 'إنشاء وتعديل سندات القيد اليومية اليدوية',
        nameEn: 'Create & Edit Manual Journal Entries',
        nameTr: 'Yevmiye Fişi Oluştur ve Düzenle',
        descriptionAr: 'تحرير القيود المحاسبية اليدوية ذات القيد المزدوج المتوازن',
        descriptionEn: 'Draft balanced double-entry manual journal entries',
        descriptionTr: 'Çift taraflı dengeli manuel yevmiye kaydı oluşturma',
        action: 'create',
      },
      {
        code: 'journal_entries.post',
        module: 'accounting',
        nameAr: 'ترحيل القيود وإلغاء ترحيلها وقفل الفترات',
        nameEn: 'Post / Void Journal Entries & Period Close',
        nameTr: 'Yevmiye Kayıtlarını Onayla / İptal Et',
        descriptionAr: 'ترحيل سندات القيد إلى الأستاذ العام أو إلغاء القيود وإقفال الفترات',
        descriptionEn: 'Post entries to permanent general ledger and manage accounting lock dates',
        descriptionTr: 'Yevmiye fişlerini kesinleştirme ve dönem kapatma yetkisi',
        action: 'post',
      },
    ],
  },
  {
    moduleId: 'expenses',
    nameAr: 'المصروفات وسندات الصرف',
    nameEn: 'Expenses & Vouchers',
    nameTr: 'Giderler ve Harcamalar',
    icon: 'Receipt',
    permissions: [
      {
        code: 'expenses.view',
        module: 'expenses',
        nameAr: 'عرض سجل المصروفات وسندات الصرف',
        nameEn: 'View Expenses & Vouchers',
        nameTr: 'Giderleri ve Harcamaları Gör',
        descriptionAr: 'استعراض قائمة المصروفات التشغيلية وسندات الصرف',
        descriptionEn: 'View company operational expenses and expense vouchers',
        descriptionTr: 'İşletme gider listesini ve harcama makbuzlarını görme',
        action: 'view',
      },
      {
        code: 'expenses.create',
        module: 'expenses',
        nameAr: 'تسجيل واعتماد المصروفات وسندات الصرف',
        nameEn: 'Record & Approve Expenses',
        nameTr: 'Gider Girişi ve Onay',
        descriptionAr: 'تسجيل المصاريف اليومية وتحديد بنود التكلفة وخصمها من الخزائن',
        descriptionEn: 'Record daily expenses, assign cost categories and draw from cash/bank',
        descriptionTr: 'Yeni gider kaydetme ve kasa/bankadan harcama çıkışı yapma',
        action: 'create',
      },
      {
        code: 'expenses.delete',
        module: 'expenses',
        nameAr: 'إلغاء وحذف سندات المصروفات',
        nameEn: 'Cancel & Delete Expenses',
        nameTr: 'Gider Kaydını İptal Et / Sil',
        descriptionAr: 'إلغاء قيود وسندات المصروفات الخاطئة',
        descriptionEn: 'Void or remove erroneous expense records',
        descriptionTr: 'Hatalı gider kayıtlarını iptal etme veya silme',
        action: 'delete',
      },
    ],
  },
  {
    moduleId: 'reports',
    nameAr: 'التقارير المالية والتحليلية',
    nameEn: 'Financial Reports & Analytics',
    nameTr: 'Mali Raporlar ve Analizler',
    icon: 'BarChart3',
    permissions: [
      {
        code: 'reports.financial_view',
        module: 'reports',
        nameAr: 'الاطلاع على القوائم المالية الرسمية (الميزانية، الأرباح، التدفقات)',
        nameEn: 'View Financial Statements (BS, P&L, Cash Flow)',
        nameTr: 'Finansal Tabloları Gör (Bilanço, Gelir Tablosu)',
        descriptionAr: 'استعراض الميزانية العمومية، قائمة الدخل، وقائمة التدفقات النقدية',
        descriptionEn: 'View Balance Sheet, Income Statement (P&L) and Cash Flow Statements',
        descriptionTr: 'Bilanço, Gelir Tablosu ve Nakit Akış tablolarını görüntüleme',
        action: 'view',
      },
      {
        code: 'reports.operational_view',
        module: 'reports',
        nameAr: 'عرض التقارير التشغيلية (المبيعات، أعمار الديون، المخزون)',
        nameEn: 'View Operational Reports (Sales, Aging, Inventory)',
        nameTr: 'Operasyonel Raporları Gör',
        descriptionAr: 'استعراض تقارير أعمار الديون، أرباح المبيعات، ومعدلات دوران المخزون',
        descriptionEn: 'View AR/AP aging reports, sales performance and stock movement reports',
        descriptionTr: 'Yaşlandırma, satış performansı ve stok hareket raporlarını görme',
        action: 'view',
      },
      {
        code: 'reports.export',
        module: 'reports',
        nameAr: 'تصدير وطباعة التقارير (Excel / PDF)',
        nameEn: 'Export & Print Financial Data',
        nameTr: 'Raporları Dışa Aktar (Excel/PDF)',
        descriptionAr: 'تنزيل وتصدير التقارير والقوائم إلى ملفات إكسل وطباعتها',
        descriptionEn: 'Export data tables and financial statements to Excel or print PDF',
        descriptionTr: 'Mali raporları Excel veya PDF olarak indirme ve yazdırma',
        action: 'export',
      },
    ],
  },
  {
    moduleId: 'settings',
    nameAr: 'إعدادات المنشأة والمستخدمين والنظام',
    nameEn: 'Settings & Administration',
    nameTr: 'Ayarlar ve Sistem Yönetimi',
    icon: 'Settings',
    permissions: [
      {
        code: 'settings.manage',
        module: 'settings',
        nameAr: 'تعديل الإعدادات العامة والعملات والضرائب والترقيم',
        nameEn: 'Manage Business Settings, Taxes & Currencies',
        nameTr: 'Şirket, Vergi ve Para Birimi Ayarları',
        descriptionAr: 'تعديل بيانات المنشأة القانونية، أسعار الصرف، والضرائب وترقيم المستندات',
        descriptionEn: 'Update business profile, tax rates, currencies and document numbering',
        descriptionTr: 'Şirket profili, vergi oranları ve para birimlerini yönetme',
        action: 'manage',
      },
      {
        code: 'members.manage',
        module: 'settings',
        nameAr: 'إدارة المستخدمين وإنشاء الحسابات وتخصيص الصلاحيات',
        nameEn: 'Manage Team Members, Passwords & Access Controls',
        nameTr: 'Kullanıcı ve Yetki Yönetimi',
        descriptionAr: 'إضافة المستخدمين المباشرين، تعيين كلمات المرور، وتخصيص الصلاحيات',
        descriptionEn: 'Add direct users, assign credentials and customize granular permissions',
        descriptionTr: 'Doğrudan kullanıcı ekleme, şifre belirleme ve yetkilendirme yapma',
        action: 'manage',
      },
      {
        code: 'audit.view',
        module: 'settings',
        nameAr: 'استعراض سجل الرقابة والتدقيق الأمني (Audit Logs)',
        nameEn: 'View Audit Logs & Security History',
        nameTr: 'Denetim Günlüklerini (Audit Log) Gör',
        descriptionAr: 'متابعة سجل حركات وتعديلات المستخدمين والعمليات الحساسة في النظام',
        descriptionEn: 'Review full chronological audit trail and user action history',
        descriptionTr: 'Tüm kullanıcı işlem geçmişini ve güvenlik kayıtlarını inceleme',
        action: 'view',
      },
    ],
  },
]

// All permission codes flattened
export const ALL_PERMISSION_CODES: string[] = SYSTEM_PERMISSIONS_REGISTRY.flatMap(
  (group) => group.permissions.map((p) => p.code)
)

// Default permissions assigned to each standard role preset
export const ROLE_PRESET_PERMISSIONS: Record<string, string[]> = {
  owner: [...ALL_PERMISSION_CODES],
  administrator: [...ALL_PERMISSION_CODES],
  accountant: [
    'sales.view',
    'sales.create',
    'sales.edit',
    'sales.returns',
    'purchases.view',
    'purchases.create',
    'purchases.edit',
    'customers.view',
    'customers.manage',
    'suppliers.view',
    'suppliers.manage',
    'inventory.view',
    'inventory.adjust',
    'treasury.view',
    'payments.incoming',
    'payments.outgoing',
    'treasury.transfers',
    'treasury.reconcile',
    'accounting.view',
    'accounting.chart_manage',
    'journal_entries.create',
    'journal_entries.post',
    'expenses.view',
    'expenses.create',
    'expenses.delete',
    'reports.financial_view',
    'reports.operational_view',
    'reports.export',
  ],
  sales_user: [
    'sales.view',
    'sales.create',
    'sales.edit',
    'sales.returns',
    'customers.view',
    'customers.manage',
    'inventory.view',
    'payments.incoming',
    'reports.operational_view',
  ],
  purchase_user: [
    'purchases.view',
    'purchases.create',
    'purchases.edit',
    'suppliers.view',
    'suppliers.manage',
    'inventory.view',
    'payments.outgoing',
    'reports.operational_view',
  ],
  inventory_user: [
    'inventory.view',
    'inventory.manage',
    'inventory.adjust',
    'sales.view',
    'purchases.view',
    'reports.operational_view',
  ],
  viewer: [
    'sales.view',
    'purchases.view',
    'customers.view',
    'suppliers.view',
    'inventory.view',
    'treasury.view',
    'accounting.view',
    'expenses.view',
    'reports.operational_view',
  ],
  custom: [],
}

/**
 * Check if a permission code exists in a given permission set.
 */
export function hasCode(permissions: string[] | Record<string, boolean> | null | undefined, code: string): boolean {
  if (!permissions) return false
  if (Array.isArray(permissions)) {
    return permissions.includes(code) || permissions.includes('*')
  }
  if (typeof permissions === 'object') {
    return permissions[code] === true || permissions['*'] === true
  }
  return false
}
